[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/api/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
NODE_ENV = "production"
PYTHON_VERSION = "3.11.0"
ENVIRONMENT = "production"
PLATFORM = "railway"
ENABLE_MONITORING = "true"
ENABLE_LOGGING = "true"
ANTI_DETECTION_ENABLED = "true"
FINGERPRINT_ROTATION = "true"
DEVICE_ROTATION = "true"
SESSION_TIMEOUT = "3600"
MAX_RETRIES = "3"
CONFIG_SOURCE = "json"
ACCOUNTS_FILE = "config/accounts.json"
CAPTIONS_FILE = "assets/captions.txt"
IMAGES_DIR = "assets/images/"
USER_AGENTS_FILE = "config/user_agents.txt"
LOG_LEVEL = "INFO"
GLOBAL_IMAGE_COOLDOWN = "1800"
ACCOUNT_IMAGE_COOLDOWN = "3600"
MAX_ACCOUNT_HISTORY = "5"
CLEANUP_MAX_AGE_HOURS = "24" 