[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run railway-start"
healthcheckPath = "/api/status"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production" 