[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/api/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[deploy.environment]
PLATFORM = "railway"
ENVIRONMENT = "production"
ANTI_DETECTION_ENABLED = "true"
SESSION_TIMEOUT = "3600"
MAX_RETRIES = "3"
LOG_LEVEL = "INFO"
ACCOUNTS_FILE = "config/accounts.json"
CAPTIONS_FILE = "assets/captions.txt"
IMAGES_DIR = "assets/images/"
USER_AGENTS_FILE = "config/user_agents.txt" 